service: sqs-lambda-crud

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    QUEUE_URL: 
      Ref: MyQueue
  iamRoleStatements: # permissions for all of lambda functions is set here
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource: 
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:my-sqs-queue

functions:
  addMessage:
    handler: addMessage.addMessageFunc
    events:
      - http:
          path: message
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    environment:
      QUEUE_URL:
        Ref: MyQueue

  listMessages:
    handler: listMessages.listMessagesFunc
    events:
      - http:
          path: messages
          method: get
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    environment:
      QUEUE_URL:
        Ref: MyQueue

  deleteMessage:
    handler: deleteMessage.deleteMessageFunc
    events:
      - http:
          path: message
          method: delete
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    environment:
      QUEUE_URL:
        Ref: MyQueue

  getQueueUrl:
    handler: getQueueUrl.getQueueUrlFunc
    events:
      - http:
          path: url
          method: get
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    environment:
      QUEUE_URL:
        Ref: MyQueue

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "my-sqs-queue"
